import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@chakra-ui/react";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>LAYERS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/assets/svgs/mainLogoDark.svg' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Welcome to layers
            {/* <code className={styles.code}>src/pages/index.tsx</code> */}
          </p>
          <div>
            <Button variant='primary' onClick={() => router.push("/dashboard")}>
              Enter App
            </Button>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src='/assets/svgs/layers-logo.svg'
            alt='Next.js Logo'
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <Link href='/onboarding' className={styles.card} rel='noopener noreferrer'>
            <h2>
              Signup <span>-&gt;</span>
            </h2>
            <p>Join Us </p>
          </Link>

          <a
            href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>Checkout templates that you can use</p>
          </a>

          <a
            href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2>
              Twitter <span>-&gt;</span>
            </h2>
            <p>Connect with us on Linkedin</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2>
              Linkedin <span>-&gt;</span>
            </h2>
            <p>Connect with us on Linkedin</p>
          </a>
        </div>
      </main>
    </>
  );
}
